# Generated by Django 3.2.6 on 2021-12-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aut_twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='description',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='title',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='api',
            name='completed',
        ),
    ]
