# Generated by Django 3.2.6 on 2022-01-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aut_twitter', '0003_auto_20220125_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_table',
        ),
    ]
